# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from weather_api import get_current_weather, get_hourly_forecast
from matplotlib.figure import Figure
from PyQt5.QtWidgets import QGraphicsScene
import image

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 231, 191))
        self.label.setStyleSheet("image: url(:/myimage/logo-removebg-preview.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 771, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 90, 620, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 70, 651, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 130, 651, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 550, 1041, 241))
        self.graphicsView.setObjectName("graphicsView")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 220, 301, 321))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(80, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(110, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(50, 70, 181, 151))
        self.label_8.setStyleSheet("image: url(:/myimage/sun.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(110, 280, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(390, 370, 681, 171))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(30, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(150, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(260, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(370, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(480, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(590, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(50, 150, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(170, 150, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(280, 150, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(390, 150, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(500, 150, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(600, 150, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(120, 10, 20, 161))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(230, 10, 20, 161))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(340, 10, 20, 161))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setGeometry(QtCore.QRect(450, 10, 20, 161))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(560, 10, 20, 161))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(20, 50, 91, 91))
        self.label_21.setStyleSheet("image: url(:/myimage/clouds.png);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(140, 50, 91, 91))
        self.label_22.setStyleSheet("image: url(:/myimage/sun.png);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(250, 50, 91, 91))
        self.label_23.setStyleSheet("image: url(:/myimage/rainy-day.png);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(360, 50, 91, 91))
        self.label_24.setStyleSheet("image: url(:/myimage/rainy-day.png);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(470, 50, 91, 91))
        self.label_25.setStyleSheet("image: url(:/myimage/clouds.png);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(580, 50, 91, 91))
        self.label_26.setStyleSheet("image: url(:/myimage/clouds.png);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(390, 220, 681, 141))
        self.frame_3.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(100, 40, 101, 91))
        self.label_27.setStyleSheet("image: url(:/myimage/lamp_off.png);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(330, 40, 101, 91))
        self.label_28.setStyleSheet("image: url(:/myimage/ceiling-fan-off.png);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.line_6 = QtWidgets.QFrame(self.frame_3)
        self.line_6.setGeometry(QtCore.QRect(200, 10, 20, 121))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.frame_3)
        self.line_7.setGeometry(QtCore.QRect(440, 10, 20, 121))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(570, 40, 101, 91))
        self.label_29.setStyleSheet("image: url(:/myimage/close.png);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_3)
        self.label_30.setGeometry(QtCore.QRect(90, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_3)
        self.label_31.setGeometry(QtCore.QRect(290, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_3)
        self.label_32.setGeometry(QtCore.QRect(540, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 50, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 50, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 100, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 100, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(460, 100, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.light_on)
        self.pushButton_2.clicked.connect(self.fan_on)
        self.pushButton_3.clicked.connect(self.open)
        self.pushButton_4.clicked.connect(self.light_off)
        self.pushButton_5.clicked.connect(self.fan_off)
        self.pushButton_6.clicked.connect(self.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "WEATHER FORECAST IN HO CHI MINH CITY"))
        self.label_3.setText(_translate("MainWindow", "HCMC University of Technology and Engineering"))
        self.label_4.setText(_translate("MainWindow", "========================================================================"))
        self.label_5.setText(_translate("MainWindow", "========================================================================"))
        self.label_6.setText(_translate("MainWindow", "THU DUC"))
        self.label_7.setText(_translate("MainWindow", "TEMP"))
        self.label_33.setText(_translate("MainWindow", "HUMID"))
        self.label_9.setText(_translate("MainWindow", "6:00 AM"))
        self.label_10.setText(_translate("MainWindow", "9:00 AM"))
        self.label_11.setText(_translate("MainWindow", "12:00 PM"))
        self.label_12.setText(_translate("MainWindow", "15:00 PM"))
        self.label_13.setText(_translate("MainWindow", "18:00 PM"))
        self.label_14.setText(_translate("MainWindow", "21:00 PM"))
        self.label_15.setText(_translate("MainWindow", "TEMP"))
        self.label_16.setText(_translate("MainWindow", "TEMP"))
        self.label_17.setText(_translate("MainWindow", "TEMP"))
        self.label_18.setText(_translate("MainWindow", "TEMP"))
        self.label_19.setText(_translate("MainWindow", "TEMP"))
        self.label_20.setText(_translate("MainWindow", "TEMP"))
        self.label_30.setText(_translate("MainWindow", "Light"))
        self.label_31.setText(_translate("MainWindow", "Ceiling fan"))
        self.label_32.setText(_translate("MainWindow", "Window"))
        self.pushButton.setText(_translate("MainWindow", "On"))
        self.pushButton_2.setText(_translate("MainWindow", "On"))
        self.pushButton_3.setText(_translate("MainWindow", "Open"))
        self.pushButton_4.setText(_translate("MainWindow", "Off"))
        self.pushButton_5.setText(_translate("MainWindow", "Off"))
        self.pushButton_6.setText(_translate("MainWindow", "Close"))
    
    def light_on(self):
        self.label_27.setStyleSheet("image: url(:/myimage/lamp_on.png);")
    def light_off(self):
        self.label_27.setStyleSheet("image: url(:/myimage/lamp_off.png);")

    def fan_on(self):
        self.label_28.setStyleSheet("image: url(:/myimage/ceiling-fan-on.png);")
    def fan_off(self):
        self.label_28.setStyleSheet("image: url(:/myimage/ceiling-fan-off.png);")

    def open(self):
        self.label_29.setStyleSheet("image: url(:/myimage/open.png);")
    def close(self):
        self.label_29.setStyleSheet("image: url(:/myimage/close.png);")

    def load_weather(self):
        print("LOAD WEATHER CALLED")
        data = get_current_weather()

        if data.get("cod") != 200:
            self.label_7.setText("N/A")
            return

        temp = data["main"]["temp"]
        weather = data["weather"][0]["main"]
        humidity = data["main"]["humidity"]

        self.label_7.setText(f"{temp:.1f} °C")
        self.label_33.setText(f"{humidity} %")
        from datetime import datetime

        current_hour = datetime.now().hour
        info = data["weather"][0]

        self.set_icon(
            self.label_8,
            info["main"],
            current_hour)

        forecast = get_hourly_forecast()["list"]

        temp_labels = [
            self.label_15, self.label_16, self.label_17,
            self.label_18, self.label_19, self.label_20
        ]

        icon_labels = [
            self.label_21, self.label_22, self.label_23,
            self.label_24, self.label_25, self.label_26
        ]

        for i in range(6):
            temp_labels[i].setText(f"{forecast[i]['main']['temp']:.1f} °C")

            info = forecast[i]["weather"][0]

            hour = int(forecast[i]["dt_txt"][11:13])

            self.set_icon(
                icon_labels[i],
                info["main"],
                hour
            )

    def set_icon(self, label, weather, hour):
        is_night = hour >= 18 or hour < 6

        if is_night:
            if weather == "Clear":
                label.setStyleSheet("image: url(:/myimage/moon.png);")
            elif weather == "Clouds":
                label.setStyleSheet("image: url(:/myimage/clouds.png);")
            elif weather == "Rain":
                label.setStyleSheet("image: url(:/myimage/rainy-day.png);")
            elif weather == "Thunderstorm":
                label.setStyleSheet("image: url(:/myimage/storm-night.png);")
            elif weather == "Windy":
                label.setStyleSheet("image: url(:/myimage/windy.png);")
            else:
                label.setStyleSheet("image: url(:/myimage/clouds.png);")
            return

        if weather == "Clear":
            label.setStyleSheet("image: url(:/myimage/sun.png);")
        elif weather == "Clouds":
            label.setStyleSheet("image: url(:/myimage/clouds.png);")
        elif weather == "Rain":
            label.setStyleSheet("image: url(:/myimage/rainy-day.png);")
        elif weather == "Thunderstorm":
            label.setStyleSheet("image: url(:/myimage/storm.png);")
        elif weather == "Windy":
            label.setStyleSheet("image: url(:/myimage/windy.png);")
        else:
            label.setStyleSheet("image: url(:/myimage/clouds.png);")
